BOT_TOKEN = '5407349012:AAHzRFbnnTdAAuWv6V0raA6iakYqk0uGKwc'
API_ID = '15158057'
API_HASH = '6a7956a4a75bd2ed46a021649e4c9edf'


# DATOS DEL MOODLE
#USUARIO DEL MOODLE entre las comillas
USUARIO = ''
#CONTRASEÑA DEL MOODLE entre las comillas
PASSWORD = ''
#ID DEL MOODLE
USUARIO_ID = 15158057
# PAGINA DEL MOODLE DEBE ESTAR COMO EL EJEMPLO: cursos.edu.uo.cu
MOODLE_URL = 'moodle.uclv.edu.cu'
#TAMAÑO EN LO QUE SE PICARAN LOS ZIP AL SUBIR AL MOODLE
ZIP_MB = 399
# TU ID DE TELEGRAM DENTRO DE LOS CORCHETES
OWNER = [15158057]

#PONGA AQUI PROXY ENCRIPTADO
proxy = 'socks5://KGGGJHYIJGLKFIYEKEIJCIYIJFKKEGRJCFLEGKLD'

# CUENTA DE MEGA
# GMAIL DE CUENTA DE MEGA
GMAIL_MEGA = 'yanco148@gmail.com'
PASS_MEGA = 'yancarlos1482005'
